PP.Inventory.Web/Models/Layout/LanguageSelectionViewModel.cs
using System.Collections.Generic;
using Abp.Localization;

namespace PP.Inventory.Web.Models.Layout
{
    public class LanguageSelectionViewModel
    {
        public LanguageInfo CurrentLanguage { get; set; }

        public IReadOnlyList<LanguageInfo> Languages { get; set; }
    }
}

PP.Inventory.Web/Models/Layout/TopMenuViewModel.cs
using Abp.Application.Navigation;

namespace PP.Inventory.Web.Models.Layout
{
    public class TopMenuViewModel
    {
        public UserMenu MainMenu { get; set; }

        public string ActiveMenuItemName { get; set; }
    }
}

PP.Inventory.Web/Controllers/AboutController.cs
using System.Web.Mvc;

namespace PP.Inventory.Web.Controllers
{
    public class AboutController : InventoryControllerBase
    {
        public ActionResult Index()
        {
            return View();
        }
	}
}

PP.Inventory.Web/Controllers/HomeController.cs
using System.Web.Mvc;

namespace PP.Inventory.Web.Controllers
{
    public class HomeController : InventoryControllerBase
    {
        public ActionResult Index()
        {
            return View();
        }
	}
}

PP.Inventory.Web/Controllers/LayoutController.cs
using System.Web.Mvc;
using Abp.Application.Navigation;
using Abp.Localization;
using Abp.Threading;
using PP.Inventory.Web.Models.Layout;

namespace PP.Inventory.Web.Controllers
{
    public class LayoutController : InventoryControllerBase
    {
        private readonly IUserNavigationManager _userNavigationManager;
        private readonly ILocalizationManager _localizationManager;

        public LayoutController(IUserNavigationManager userNavigationManager, ILocalizationManager localizationManager)
        {
            _userNavigationManager = userNavigationManager;
            _localizationManager = localizationManager;
        }

        [ChildActionOnly]
        public PartialViewResult TopMenu(string activeMenu = "")
        {
            var model = new TopMenuViewModel
                        {
                            MainMenu = AsyncHelper.RunSync(() => _userNavigationManager.GetMenuAsync("MainMenu", AbpSession.UserId)),
                            ActiveMenuItemName = activeMenu
                        };

            return PartialView("_TopMenu", model);
        }

        [ChildActionOnly]
        public PartialViewResult LanguageSelection()
        {
            var model = new LanguageSelectionViewModel
                        {
                            CurrentLanguage = _localizationManager.CurrentLanguage,
                            Languages = _localizationManager.GetAllLanguages()
                        };

            return PartialView("_LanguageSelection", model);
        }
    }
}

PP.Inventory.Web/Controllers/StockController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PP.Inventory.Web.Controllers
{
    public class StockController : Controller
    {
        // GET: Stock
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult StockSearch()
        {
            return View();
        }
        public ActionResult UpdateStock()
        {
            return View();
        }
        public JsonResult GetStock()
        {
            string spage = Request.Params["page"];//查询的页数
            string srows = Request.Params["rows"];//每页的数据数

            string sidx = Request.Params["sidx"];//排序列名
            string sord = Request.Params["sord"];//排序方式

            //GridDataModel model = new GridDataModel();
            //List<SampleDto> list = new List<SampleDto>();
            //list.Add(new SampleDto
            //{
            //    StyleCode = "STYLE001",
            //    StyleName = "一般",
            //    SaleAmt = 10000,
            //    SaleQty = 1200,
            //    UseYN = "Y",
            //    Season = "SP",
            //    SaleDate = Convert.ToDateTime("2014-11-22")
            //});
            //list.Add(new SampleDto
            //{
            //    StyleCode = "STYLE002",
            //    StyleName = "儿童",
            //    SaleAmt = 10000,
            //    SaleQty = 1200,
            //    UseYN = "Y",
            //    Season = "AU",
            //    SaleDate = Convert.ToDateTime("2014-11-24")
            //});
            //model.data = list;
            //model.page = 2; //查询的页数
            //model.records = 100; //全部数据数
            //model.total = 11; //页面数
            return Json(new { data = "model" }, JsonRequestBehavior.AllowGet);

        }
    }
}

PP.Inventory.Web/Views/About/Index.cshtml
@{
    ViewBag.ActiveMenu = "About"; //The menu item will be active for this page.
}
<div>
    <h1><img src="~/images/abp-logo.png" style="padding-right: 10px;" />@string.Format(L("AboutFormat"), "ASP.NET Boilerplate")</h1>
    <p>@Html.Raw(L("About_AspNetBoilerplateDescription"))</p>
    <p>@L("ForMoreInformation"): <a href="http://www.aspnetboilerplate.com"><strong>aspnetboilerplate.com</strong></a>.</p>
</div>

PP.Inventory.Web/Views/Home/Index.cshtml
@{
    ViewBag.ActiveMenu = "Home"; //The menu item will be active for this page.
}
<div>
    <h1>@L("WellcomeMessage")!</h1>
    <p class="lead">@L("Home_ThisIsATemplate")</p>
    <div class="row">
        <div class="col-md-4">
            <h3>ASP.NET MVC</h3>
            <p>
                @L("Home_AspNetDescription")
            </p>
            <a class="btn btn-primary btn-sm" href="http://asp.net/mvc">@L("LearnMore")..</a>
        </div>
        <div class="col-md-4">
            <h3>ASP.NET Boilerplate</h3>
            <p>
                @L("Home_AspNetBoilerplateDescription")
            </p>
            <a class="btn btn-primary btn-sm" href="http://aspnetboilerplate.com">@L("LearnMore")..</a>
        </div>
        <div class="col-md-4">
            <h3>@L("Others")</h3>
            <p>
                @L("Home_OtherTools")
            </p>
        </div>
    </div>
</div>

PP.Inventory.Web/Views/Layout/_LanguageSelection.cshtml
@model PP.Inventory.Web.Models.Layout.LanguageSelectionViewModel
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <i class="@Model.CurrentLanguage.Icon"></i>
        <span>@Model.CurrentLanguage.DisplayName</span>
        <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
        @foreach (var language in Model.Languages)
        {
            if (language.Name != Model.CurrentLanguage.Name)
            {
                <li><a href="@Url.Action("ChangeCulture", "AbpLocalization")?cultureName=@(language.Name)&returnUrl=@(Request.Url)"><i class="@language.Icon"></i> @language.DisplayName</a></li>
            }
        }
    </ul>
</li>

PP.Inventory.Web/Views/Layout/_TopMenu.cshtml
@using Abp.Collections.Extensions
@model PP.Inventory.Web.Models.Layout.TopMenuViewModel
@foreach (var menuItem in Model.MainMenu.Items)
{
    <li class="@(Model.ActiveMenuItemName == menuItem.Name ? "active" : "")">
        @if (menuItem.Items.IsNullOrEmpty())
        {
            <a href="@menuItem.Url">
                @if (!string.IsNullOrWhiteSpace(menuItem.Icon))
                {
                    <i class="@menuItem.Icon"></i>
                }
                @menuItem.DisplayName
            </a>
        }
        else
        {
            <a href="" data-toggle="dropdown">
                @if (!string.IsNullOrWhiteSpace(menuItem.Icon))
                {
                    <i class="@menuItem.Icon"></i>
                }
                @menuItem.DisplayName
            </a>
            <ul class="dropdown-menu">
                @foreach (var subMenuItem in menuItem.Items)
                {
                    <li>
                        <a href="@subMenuItem.Url">
                            @if (!string.IsNullOrWhiteSpace(subMenuItem.Icon))
                            {
                                <i class="@subMenuItem.Icon"></i>
                            }
                            @subMenuItem.DisplayName
                        </a>
                    </li>
                }
            </ul>
        }
    </li>
}

PP.Inventory.Web/Views/Shared/_Layout.cshtml
@using System.Threading
@using System.Web.Optimization
@using Abp.Timing
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="shortcut icon" href="~/favicon.ico">

    <title>Inventory</title>

    @Styles.Render("~/Bundles/vendor/css")
    @Styles.Render("~/Bundles/css")

    <!-- View specific styles -->
    @RenderSection("styles", required: false)

    <script type="text/javascript">
        //This is used to get the application's root path from javascript. It's useful if you're running application in a virtual directory under IIS.
        var abp = abp || {}; abp.appPath = '@ApplicationPath';
    </script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="@Url.Content("~/Scripts/others/html5shiv.js")"></script>
        <script src="@Url.Content("~/Scripts/others/respond.min.js")"></script>
    <![endif]-->

    @Scripts.Render("~/Bundles/vendor/js/top")

</head>
<body>
    @Html.Partial("_TopBar")

    <div class="container">
        @RenderBody()
    </div>

    @Scripts.Render("~/Bundles/vendor/js/bottom")
    @Scripts.Render("~/Bundles/js")

    <script>
        abp.localization.defaultSourceName = '@LocalizationSourceName';
        moment.locale('@Thread.CurrentThread.CurrentUICulture.Name'); //Localizing momentjs
    </script>

    <!-- Dynamic scripts of ABP system (They are created on runtime and can not be bundled) -->
    <script src="~/api/AbpServiceProxies/GetAll?v=@(Clock.Now.Ticks)"></script>
    <script src="~/AbpScripts/GetScripts?v=@(Clock.Now.Ticks)" type="text/javascript"></script>

    <!-- View specific scripts -->
    @RenderSection("scripts", required: false)
</body>
</html>

PP.Inventory.Web/Views/Shared/_TopBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="~/"><i class="fa fa-cubes"></i> Inventory</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                @Html.Action("TopMenu", "Layout", new { activeMenu = ViewBag.ActiveMenu })
            </ul>
            <ul class="nav navbar-nav navbar-right">
                @Html.Action("LanguageSelection", "Layout")
            </ul>
        </div>
    </div>
</div>

PP.Inventory.Web/Views/Stock/UpdateStock.cshtml

@{
    ViewBag.Title = "UpdateStock";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>UpdateStock</h2>
@section Scripts{
            <script src="~/Scripts/jquery.jqGrid.js" type="text/javascript"></script>
            <script src="" type="text/javascript"></script>
            <script src="~/Scripts/lang/grid.locale-zh-CN.js"></script>
            <link href="~/Content/ui.jqgrid.css" rel="stylesheet" />
            <script type="text/javascript">
                        function Initialize()
                        {
                            _gridStyle = 'gridStyle';
                            _grid = $('#' + _gridStyle);
                        }
                        function InitData()
                        {
                            var collist = Fetch_column();
                            fn_grid_init("",collist);
                            var data = fn_create_sampledata();
                            Set_Grid(data);
                        }
            </script>
            <script type="text/javascript">
            function Fetch_column()
            {
                var list = [];
                list.push({
                    name: "id", label: "序列", width: 100, align: "center",
                    cellattr: function (rowId, val, rawObject, cm, rdata) {
                        return 'class="readonlycell"';
                    }
                });
                list.push({
                    name: 'prodCode', label: '代码', width: 100, align: 'center',
                    cellattr: function (rowId, val, rawObject, cm, rdata) {
                        return 'class="readonlycell"';
                    }
                });
                list.push({
                    name: 'brandcode', label: '品牌', width: 100, align: 'center',
                    cellattr: function (rowId, val, rawObject, cm, rdata) {
                        return 'class="readonlycell"';
                    }
                });
                list.push({
                    name: 'prodname', label: '商品名', width: 100, align: 'center',
                    cellattr: function (rowId, val, rawObject, cm, rdata) {
                        return 'class="readonlycell"';
                    }
                });
                list.push({
                    name: 'size', label: '尺寸', width: 70, align: 'left',
                    editable: true,
                    edittype: 'text',
                    editoptions: {
                        'class': 'text-center',
                        maxlength: 10 //<input type='text' class='',style="",maxlength="10"...
                    }
                });
                list.push({
                    name: 'color', label: '颜色', width: 90, align: 'right',
                    formatter: 'number', formatoptions: { decimalPlaces: 2 },
                    cellattr: function (rowId, val, rawObject, cm, rdata) {
                        return 'class="readonlycell"';
                    }
                });
                list.push({
                    name: 'count', label: '数量', width: 70, align: 'right',
                    formatter: 'integer', formatoptions: { decimalPlaces: 0 },
                    editable: true,
                    edittype: 'text',
                    editoptions: {
                        'class': 'text-right',//text-align:right;
                        maxlength: 18
                    }
                });
                return list;
            }
            </script>
    }
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="col-sm-12">

                <div>
                    <div class="col-sm-6">
                        <div>
                            <label>商品名</label>
                            <select>
                                <option>ELAND(CN)</option>
                                <option>SPAO</option>
                            </select>
                        </div>
                        <div>
                            <label>品牌</label>
                            <select>
                                <option>ELAND(CN)</option>
                                <option>SPAO</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="">
                            <table id="gridStyle"></table>
                            <div id="pagerStyle"></div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-12">
                    <button type="button" class="btn btn-info" id="btnSearch"><i class="fa fa-search"></i> 查询</button>
                </div>
            </div>

        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="">
                <table id="gridProd"></table>
                <div id="pagerProduct"></div>
            </div>
        </div>
    </div>
</div>